-- auth_schema.sql
-- Script para crear tablas de autenticación y autorización en Oracle
-- Ajusta el OWNER/SCHEMA si es necesario.

-- Tabla roles
CREATE TABLE roles (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR2(100) NOT NULL UNIQUE,
  descripcion VARCHAR2(4000),
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- Tabla usuarios
CREATE TABLE usuarios (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario VARCHAR2(100) NOT NULL UNIQUE,
  email VARCHAR2(200) UNIQUE,
  password_hash VARCHAR2(200) NOT NULL,
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- Tabla relacion usuarios - roles (many-to-many)
CREATE TABLE usuarios_roles (
  usuario_id NUMBER NOT NULL,
  rol_id NUMBER NOT NULL,
  asignado_en TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT fk_ur_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
  CONSTRAINT fk_ur_rol FOREIGN KEY (rol_id) REFERENCES roles(id) ON DELETE CASCADE
);

-- Índices útiles
CREATE INDEX idx_usuarios_usuario ON usuarios(usuario);
CREATE INDEX idx_roles_nombre ON roles(nombre);

-- Ejemplo: insertar rol admin y usuario de ejemplo
INSERT INTO roles (nombre, descripcion) VALUES ('ADMIN', 'Administrador del sistema');
INSERT INTO roles (nombre, descripcion) VALUES ('USER', 'Usuario normal');

-- Nota: no insertar contraseñas en texto plano.
-- Genera el hash con bcrypt desde el backend o desde Node REPL:
-- node -e "const bcrypt=require('bcrypt'); bcrypt.hash('tu_password',10).then(h=>console.log(h));"
-- Luego inserta el usuario con el hash resultante:
-- INSERT INTO usuarios (usuario, email, password_hash, activo) VALUES ('admin', 'admin@local', '<bcrypt-hash>', 1);
-- Finalmente asigna rol:
-- INSERT INTO usuarios_roles (usuario_id, rol_id) VALUES (
--   (SELECT id FROM usuarios WHERE usuario='admin'),
--   (SELECT id FROM roles WHERE nombre='ADMIN')
-- );

COMMIT;

